version: "3.8"
services:
  db:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: clien
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"